linters:
  enable:
    - gofmt
    - govet
    - revive
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - goconst
    - goimports
    - misspell
    - unparam
  disable:
    - golint

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
    - internal/infrastructure/repository/mocks
    - internal/infrastructure/storage/mocks
    - internal/infrastructure/queue/mocks
    - internal/infrastructure/converter/mocks
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 