linters:
  enable:
    - gofmt
    - govet
    - golint
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - goconst
    - goimports
    - misspell
    - unparam

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - internal/infrastructure/repository/mocks
    - internal/infrastructure/storage/mocks
    - internal/infrastructure/queue/mocks
    - internal/infrastructure/converter/mocks

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 