// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ardfard/sb-test/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockPhraseRepository is an autogenerated mock type for the PhraseRepository type
type MockPhraseRepository struct {
	mock.Mock
}

type MockPhraseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPhraseRepository) EXPECT() *MockPhraseRepository_Expecter {
	return &MockPhraseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, phrase
func (_m *MockPhraseRepository) Create(ctx context.Context, phrase *entity.Phrase) (*entity.Phrase, error) {
	ret := _m.Called(ctx, phrase)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Phrase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Phrase) (*entity.Phrase, error)); ok {
		return rf(ctx, phrase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Phrase) *entity.Phrase); ok {
		r0 = rf(ctx, phrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Phrase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Phrase) error); ok {
		r1 = rf(ctx, phrase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPhraseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPhraseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - phrase *entity.Phrase
func (_e *MockPhraseRepository_Expecter) Create(ctx interface{}, phrase interface{}) *MockPhraseRepository_Create_Call {
	return &MockPhraseRepository_Create_Call{Call: _e.mock.On("Create", ctx, phrase)}
}

func (_c *MockPhraseRepository_Create_Call) Run(run func(ctx context.Context, phrase *entity.Phrase)) *MockPhraseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Phrase))
	})
	return _c
}

func (_c *MockPhraseRepository_Create_Call) Return(_a0 *entity.Phrase, _a1 error) *MockPhraseRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPhraseRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Phrase) (*entity.Phrase, error)) *MockPhraseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPhraseRepository) GetByID(ctx context.Context, id uint) (*entity.Phrase, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Phrase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.Phrase, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Phrase); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Phrase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPhraseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPhraseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPhraseRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockPhraseRepository_GetByID_Call {
	return &MockPhraseRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPhraseRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockPhraseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockPhraseRepository_GetByID_Call) Return(_a0 *entity.Phrase, _a1 error) *MockPhraseRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPhraseRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*entity.Phrase, error)) *MockPhraseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPhraseRepository creates a new instance of MockPhraseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPhraseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPhraseRepository {
	mock := &MockPhraseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
