// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, objectName
func (_m *MockStorage) Delete(ctx context.Context, objectName string) error {
	ret := _m.Called(ctx, objectName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, objectName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - objectName string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, objectName interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, objectName)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, objectName string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, objectName
func (_m *MockStorage) Download(ctx context.Context, objectName string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, objectName)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, objectName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, objectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - objectName string
func (_e *MockStorage_Expecter) Download(ctx interface{}, objectName interface{}) *MockStorage_Download_Call {
	return &MockStorage_Download_Call{Call: _e.mock.On("Download", ctx, objectName)}
}

func (_c *MockStorage_Download_Call) Run(run func(ctx context.Context, objectName string)) *MockStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Download_Call) Return(_a0 io.ReadCloser, _a1 error) *MockStorage_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Download_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, objectName, reader
func (_m *MockStorage) Upload(ctx context.Context, objectName string, reader io.Reader) error {
	ret := _m.Called(ctx, objectName, reader)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, objectName, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectName string
//   - reader io.Reader
func (_e *MockStorage_Expecter) Upload(ctx interface{}, objectName interface{}, reader interface{}) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, objectName, reader)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, objectName string, reader io.Reader)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(_a0 error) *MockStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader) error) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
