name: Smoke Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  smoke-test:
    name: Run Smoke Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3


    - name: Make scripts executable
      run: |
        chmod +x scripts/run.sh
        chmod +x scripts/smoke_test.sh

    - name: Run smoke test
      run: ./scripts/run.sh 